:_mod-docs-content-type: ASSEMBLY
[id="persistent-storage-csi-gcp-pd"]
= GCP PD CSI Driver Operator
include::../includes/common-attributes.adoc[]
include::../includes/attributes-openshift-dedicated.adoc[]
:context: persistent-storage-csi-gcp-pd


== Overview

{product-title} can provision persistent volumes (PVs) using the Container Storage Interface (CSI) driver for Google Cloud Platform (GCP) persistent disk (PD) storage.

:FeatureName: GCP PD CSI Driver Operator

Familiarity with xref:understanding-persistent-storage[persistent storage] and xref:persistent-storage-csi[configuring CSI volumes] is recommended when working with a Container Storage Interface (CSI) Operator and driver.

To create CSI-provisioned persistent volumes (PVs) that mount to GCP PD storage assets, {product-title} installs the GCP PD CSI Driver Operator and the GCP PD CSI driver by default in the `openshift-cluster-csi-drivers` namespace.

* *GCP PD CSI Driver Operator*: By default, the Operator provides a storage class that you can use to create PVCs. You can disable this default storage class if desired (see xref:persistent-storage-csi-sc-manage[Managing the default storage class]). You also have the option to create the GCP PD storage class as described in xref:persistent-storage-using-gce[Persistent storage using GCE Persistent Disk].

* *GCP PD driver*: The driver enables you to create and mount GCP PD PVs.
//
+
GCP PD CSI driver supports the C3 instance type for bare metal and N4 machine series. The C3 instance type and N4 machine series support the hyperdisk-balanced disks. For more information, see Section _C3 instance type for bare metal and N4 machine series_.

ifndef::openshift-dedicated[]
[NOTE]
====
{product-title} provides automatic migration for the GCE Persistent Disk in-tree volume plugin to its equivalent CSI driver. For more information, see xref:../../storage/container_storage_interface/persistent-storage-csi-migration.adoc#persistent-storage-csi-migration[CSI automatic migration].
====
endif::openshift-dedicated[]

include::../includes/persistent-storage-csi-about.adoc[leveloffset=+1]

include::../includes/persistent-storage-csi-gcp-pd-reduce-permissions.adoc[leveloffset=+1]

include::../includes/persistent-storage-csi-gcp-pd-storage-class-ref.adoc[leveloffset=+1]

[id="c3-instance-type-for-bare-metal-and-n4-machine-series"]
== C3 instance type for bare metal and N4 machine series

include::../includes/persistent-storage-csi-gcp-hyperdisk-limitations.adoc[leveloffset=+2]

include::../includes/persistent-storage-csi-gcp-hyperdisk-storage-pools-overview.adoc[leveloffset=+2]

To set up storage pools, see xref:persistent-storage-csi-gcp-hyperdisk-storage-pools-procedure_persistent-storage-csi-gcp-pd[Setting up hyperdisk-balanced disks].

include::../includes/persistent-storage-csi-gcp-hyperdisk-storage-pools-procedure.adoc[leveloffset=+2]

ifndef::openshift-dedicated[]
[id="resources-for-gcp-c3-n4-instances"]
[role="_additional-resources"]
=== Additional resources
* xref:../../installing/installing_gcp/installing-gcp-customizations.adoc#installing-gcp-customizations[Installing a cluster on GCP with customizations]
endif::openshift-dedicated[]

include::../includes/persistent-storage-csi-gcp-pd-encrypted-pv.adoc[leveloffset=+1]

ifndef::openshift-rosa,openshift-dedicated[]
include::modules/persistent-storage-byok.adoc[leveloffset=+1]

For information about installing with user-managed encryption for GCP PD, see xref:../../installing/installing_gcp/installing-gcp-customizations.adoc#installation-configuration-parameters_installing-gcp-customizations[Installation configuration parameters].
endif::openshift-rosa,openshift-dedicated[]

[id="resources-for-gcp"]
[role="_additional-resources"]
== Additional resources
* xref:persistent-storage-using-gce[Persistent storage using GCE Persistent Disk]
* xref:persistent-storage-csi[Configuring CSI volumes]
